server:
  port: 8763

spring:
  profiles: peer3
  application:
    name: eureka-server
    instance_id: ${server.port}

eureka:
  instance:
    hostname: eureka-peer3
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-peer1:8761/eureka/,http://eureka-peer2:8762/eureka/
    instance:
        metadataMap:
          instanceId: ${spring.application.name}:${euraka.instance.hostname}:${spring.application.instance_id}
