server:
  port: 8763

spring:
  profiles: peer3
  application:
    name: eureka-server
    instance_id: ${server.port}

eureka:
  instance:
#    hostname: eureka-peer3
  client:
#    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    instance:
        metadataMap:
          instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
