server:
  port: 8762

spring:
  profiles: peer2
  application:
    name: eureka-server
    instance_id: ${server.port}

eureka:
  instance:
    hostname: eureka-peer2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-peer1:8761/eureka/,http://eureka-peer3:8763/eureka/
    instance:
        metadataMap:
          instanceId: ${spring.application.name}:${euraka.instance.hostname}:${spring.application.instance_id}
