server:
  port: 8761

spring:
  profiles: peer1
  application:
    name: eureka-server
    instance_id: ${server.port}

eureka:
  instance:
#    hostname: eureka-peer1
  client:
#    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/,http://localhost:8763/eureka/
    instance:
        metadataMap:
          instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
